---
collections:
  - name: community.general
    version: ">=10.0.0"
  - name: community.proxmox
    version: ">=1.4.0"  # New home for proxmox modules
  - name: ansible.posix
    version: ">=2.0.0"
  - name: community.crypto
    version: ">=3.0.0"
  - name: infisical.vault
    version: ">=1.1.0"
